### ISSUE TITLE
Start in 0.1.0 (at least)

### ISSUE THREAD

**Issue by DiegoRBaquero** [alxhotel/webtorrent-health#1]
Versions before 1.0.0 handle semver differently with caret (Default range operator)

TL;DR: 0.x is a major version and 0.0.x is a minor version. 
Full: https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004

It's best to start in 1.0.0 once the API is stable.

See: https://docs.npmjs.com/getting-started/semantic-versioning#semver-for-publishers

**Comment by alxhotel** [comment]
You are right.

Version bumped to 1.0.0: https://github.com/alxhotel/webtorrent-health/commit/a8c3d4ee5b86443cf2e44e4fa2fce5c485b4f96a

Thanks!
