### ISSUE TITLE
how do you arrive at leechers?

### ISSUE THREAD

**Issue by ralyodio** [alxhotel/webtorrent-health#4]
I see the following, but I'm curious how I arrive at seeders vs. leechers from this?

```
health:
     { seeds: 24,
       peers: 463 }
```

I am assuming `seeds` are the nodes which have 100% of the file and peers have less than 100% of the file?

**Comment by alxhotel** [comment]
Yeah.

`seeds`: nodes with 100% of the file and are uploading it.
`peers`:  nodes that don't have the complete file and are still downloading the file.

Both of them are calculated by doing the average of all the `peers` or `seeds` from all the listed trackers.
